### ISSUE TITLE
导入Integer 类型转换异常

### ISSUE THREAD

**Issue by TomYule** [1015770492/excel-import-export#1]
导入
    /** 是否已入库 */
    @ExcelCellBind(title = "是否已入库",replaceAll = true)
    @MapEntry(key = "是", value = "1")
    @MapEntry(key = "否", value = "0")
    @ApiModelProperty(value = "是否已入库")
    private java.lang.Integer regulated;

**Comment by 1015770492** [comment]
issue已收到，会尽快修复。
可否提供更多的详细信息呢，方便我尽快的更新上去。
我的邮箱：1015770492@qq.com
***
excel-import-export 我有重构的打算，这个问题应该会顺手fix

**Comment by 1015770492** [comment]
我看了一下代码，导入的demo中有Integer的例子，但看你加的信息，感觉有点奇怪，Integer 是jdk自带的，一般不需要 
java.lang.Integer 去引用类。
可否尝试下面的写法，去掉`java.lang.`

```java
@ExcelCellBind(title = "是否已入库",replaceAll = true)
@MapEntry(key = "是", value = "1")
@MapEntry(key = "否", value = "0")
@ApiModelProperty(value = "是否已入库")
private Integer regulated;
```

**Comment by 1015770492** [comment]
我看了一下代码，建议你这里导入的时候用String存这个值，不会影响你的最终数据，因为数据库有自动转义的功能。
最终你存进表里的值会将字符串转为int存入数据库中。

考虑导出的需求，数据库中存的是1和0，那么你用Integer是没有问题的。
但如果你想导出的时候自动帮你把这个1 变成 '是'，0 变成 '否' 的话，建议你还是用String来存这个字段值。这样最方便

```java
@ExcelCellBind(title = "是否已入库",replaceAll = true)
@MapEntry(key = "是", value = "1")
@MapEntry(key = "否", value = "0")
@ApiModelProperty(value = "是否已入库")
private String regulated;
```

**Comment by 1015770492** [comment]
如果问题解决了，麻烦关闭一下这个issue，最近有打算重构，生成更复杂的excel

**Comment by TomYule** [comment]
大佬厉害
